apiVersion: v1
kind: Service
metaData: 
  name: rjk8s-web-pod-svc
  labels:
    name: web
    env: test
spec:
  selector:
    name: webapp
  type: NodePort
  ports:
  - port: 80
    name: httpd
    targetPort: 80
    protocol: TCP
  
